# baseURL: http://something-fresh.org/
baseURL = "/"
languageCode = "en-us"
title = "Blog"
theme = "one"


# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    navigation = ["archives.md", "about.md"]
